### ISSUE TITLE
Broken link to GPIO usage page

### ISSUE THREAD

**Issue by LornaLynch** [raspberrypilearning/getting-started-with-mathematica#4]
The link to the GPIO usage page results in a 404 error. I can link to either of the following pages: which is preferable?
https://www.raspberrypi.org/documentation/usage/gpio-plus-and-raspi2/README.md
https://www.raspberrypi.org/documentation/usage/gpio/README.md

**Comment by LizUpton** [comment]
https://www.raspberrypi.org/documentation/usage/gpio-plus-and-raspi2/README.md please - thanks!

**Comment by LornaLynch** [comment]
Thanks, will do.

**Comment by bennuttall** [comment]
This will be a guide eventually

**Comment by LornaLynch** [comment]
Thanks
