### ISSUE TITLE
Add a note about how to install Mathmatica if not installed. (Nov 2020)

### ISSUE THREAD

**Issue by libxx1** [raspberrypilearning/getting-started-with-mathematica#8]
URL: /en/projects/getting-started-with-mathematica/3

"This assumes Mathematica is installed, you provide a version without it installed.

In fact I can find a guide on how to install software, either recommended or the full on desktop 'store' version.Could we have one so it can be linked to?"

**Comment by libxx1** [comment]
@PhilipHarney this was raised by a user. Would we just need to add the text from the bottom of this blog about installing it if it's not already installed? If so I'll add it https://www.raspberrypi.org/blog/new-wolfram-mathematica-resources-2019/

**Comment by PhilipHarney** [comment]
Sounds good! I actually didn’t write these projects, so much as edit them, so I’m not much of an expert in Wolfram. But past me does seem to have figured this specific issue out, so I’d go ahead and stick that in the projects, yeah 😄

**Comment by libxx1** [comment]
@PhilipHarney fab will do. Thank you.
